#!/usr/bin/env node
/**
 * migrate_d1_to_supabase.mjs
 * ==========================
 * Export data dari Cloudflare D1 dan import ke Supabase PostgreSQL.
 * 
 * Cara pakai:
 *   1. Export D1 dulu:
 *      npx wrangler d1 export kingshortid --output=./migration_backup/d1_export.sql
 *
 *   2. Jalankan script ini:
 *      node scripts/migrate_d1_to_supabase.mjs
 */

import postgres from 'postgres';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Supabase connection
const SUPABASE_HOST = process.env.SUPABASE_HOST || '141.11.160.187';
const SUPABASE_PASSWORD = process.env.SUPABASE_DB_PASSWORD || 'GoZViH1AXL73BqLdkDtpeGgwUzfW64';
const DB_URL = process.env.DATABASE_URL || `postgresql://postgres:${SUPABASE_PASSWORD}@${SUPABASE_HOST}:5432/postgres`;

// D1 export JSON folder (generated by wrangler d1 export --format=json)
const BACKUP_DIR = path.join(__dirname, '../migration_backup');

async function main() {
    console.log('=== D1 → Supabase Migration ===');
    console.log(`Target: ${SUPABASE_HOST}:5432/postgres\n`);

    const sql = postgres(DB_URL, { max: 5, connect_timeout: 15 });

    try {
        // Test connection
        const result = await sql`SELECT 1 as ok`;
        console.log('✅ Supabase connection OK\n');

        // Check if backup exists
        if (!fs.existsSync(BACKUP_DIR)) {
            console.log(`⚠️  Backup dir tidak ditemukan: ${BACKUP_DIR}`);
            console.log('Jalankan dulu:');
            console.log('  npx wrangler d1 export kingshortid --output=./migration_backup/d1_export.sql');
            process.exit(1);
        }

        // Load JSON exports (dari wrangler d1 export --format=json per tabel)
        const tables = [
            'categories', 'users', 'dramas', 'seasons', 'episodes', 'subtitles',
            'watchlist', 'favorites', 'collections', 'watch_history',
            'coin_transactions', 'notifications', 'achievements',
            'user_achievements', 'daily_rewards',
        ];

        const stats = { imported: 0, skipped: 0, errors: 0 };

        for (const table of tables) {
            const jsonFile = path.join(BACKUP_DIR, `${table}.json`);
            if (!fs.existsSync(jsonFile)) {
                console.log(`  ⏭️  ${table}: file tidak ada, skip`);
                stats.skipped++;
                continue;
            }

            const rows = JSON.parse(fs.readFileSync(jsonFile, 'utf-8'));
            if (!rows.length) {
                console.log(`  ⏭️  ${table}: kosong, skip`);
                continue;
            }

            console.log(`  📥 ${table}: ${rows.length} rows...`);

            try {
                // Insert in batches of 100
                const batchSize = 100;
                let inserted = 0;
                for (let i = 0; i < rows.length; i += batchSize) {
                    const batch = rows.slice(i, i + batchSize);
                    await sql`
                        INSERT INTO ${sql(table)} ${sql(batch)}
                        ON CONFLICT DO NOTHING
                    `;
                    inserted += batch.length;
                }
                console.log(`  ✅ ${table}: ${inserted} rows imported`);
                stats.imported += rows.length;
            } catch (err) {
                console.log(`  ❌ ${table}: ERROR - ${err.message}`);
                stats.errors++;
            }
        }

        console.log('\n=== HASIL ===');
        console.log(`Imported : ${stats.imported} rows`);
        console.log(`Skipped  : ${stats.skipped} tables`);
        console.log(`Errors   : ${stats.errors} tables`);

        if (stats.errors === 0) {
            console.log('\n✅ Migrasi selesai! Verifikasi di Supabase Studio:');
            console.log(`   http://${SUPABASE_HOST}:8000`);
        } else {
            console.log('\n⚠️  Ada error. Cek log di atas.');
        }

    } finally {
        await sql.end();
    }
}

main().catch(console.error);
