"""
Make LIVE API call using sign generated by the APP
"""
import frida
import requests
import time
import json

captured_data = {}

def on_message(message, data):
    global captured_data
    if message['type'] == 'send':
        payload = message['payload']
        if payload.startswith('DATA:'):
            key, value = payload[5:].split('=', 1)
            captured_data[key] = value
            print(f"Captured {key}: {value[:50]}...")
        else:
            print(payload)

script_code = """
setTimeout(function() {
    Java.perform(function() {
        var AppUtils = Java.use('com.newreading.goodreels.utils.AppUtils');
        var SpData = Java.use('com.newreading.goodreels.utils.SpData');
        
        // Use CURRENT timestamp for live call
        var ts = Date.now().toString();
        var path = '/home/index';
        
        send('Generating sign with fresh timestamp: ' + ts);
        
        // Get sign from app
        var sign = AppUtils.getSign(ts, path);
        var userToken = SpData.getUserToken();
        var gaid = AppUtils.getGAID();
        var androidId = AppUtils.getAndroidID();
        
        // Send data for API call
        send('DATA:timestamp=' + ts);
        send('DATA:sign=' + sign);
        send('DATA:userToken=' + userToken);
        send('DATA:gaid=' + gaid);
        send('DATA:androidId=' + androidId);
        
        send('');
        send('=== DATA CAPTURED ===');
    });
}, 3000);
"""

def main():
    global captured_data
    
    device = frida.get_usb_device()
    
    print("Spawning app...")
    pid = device.spawn(['com.newreading.goodreels'])
    session = device.attach(pid)
    
    script = session.create_script(script_code)
    script.on('message', on_message)
    script.load()
    
    device.resume(pid)
    
    print("Waiting for data capture...")
    time.sleep(8)
    
    print("\\n=== Making LIVE API call with captured sign ===")
    
    if 'sign' not in captured_data:
        print("ERROR: Failed to capture sign!")
        return
    
    # Make API call with app-generated sign
    url = f"https://api-akm.goodreels.com/hwycclientreels/home/index?timestamp={captured_data['timestamp']}"
    
    headers = {
        'sign': captured_data['sign'],
        'Authorization': captured_data['userToken'],
        'deviceId': captured_data['gaid'],
        'androidId': captured_data['androidId'],
        'pname': 'com.newreading.goodreels',
        'platform': 'ANDROID',
        'appVersion': '2782078',
        'Content-Type': 'application/json; charset=UTF-8',
        'User-Agent': 'okhttp/4.10.0'
    }
    
    data = {
        'pageNo': 1,
        'pageSize': 12,
        'channelType': 3,
        'vipBookEnable': True,
        'channelId': -3
    }
    
    print(f"URL: {url}")
    print(f"Sign: {captured_data['sign'][:60]}...")
    print("")
    
    try:
        response = requests.post(url, headers=headers, json=data, timeout=10)
        print(f"Status: {response.status_code}")
        print(f"Response: {response.text[:500]}")
        
        if response.status_code == 200:
            result = response.json()
            if result.get('success'):
                print("\\n🎉🎉🎉 SUCCESS!!! API CALL WORKED!!! 🎉🎉🎉")
            else:
                print(f"\\n❌ API returned error: {result.get('message')}")
        else:
            print(f"\\n❌ HTTP error: {response.status_code}")
            
    except Exception as e:
        print(f"\\n❌ Request failed: {e}")

if __name__ == '__main__':
    main()
