-- Register missing episodes 45-70 for 'Manisnya Cinta Tak Sehangat Uang'
-- Drama ID: ugg83k4tufn3vmqjtydijhy1

INSERT INTO episodes (id, "dramaId", "episodeNumber", title, "videoUrl", "videoUrl540p", duration, "isVip", "coinPrice", views, "isActive", "createdAt", "updatedAt")
VALUES
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 45, 'Episode 45', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep045.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep045_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 46, 'Episode 46', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep046.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep046_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 47, 'Episode 47', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep047.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep047_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 48, 'Episode 48', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep048.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep048_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 49, 'Episode 49', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep049.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep049_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 50, 'Episode 50', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep050.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep050_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 51, 'Episode 51', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep051.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep051_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 52, 'Episode 52', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep052.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep052_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 53, 'Episode 53', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep053.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep053_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 54, 'Episode 54', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep054.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep054_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 55, 'Episode 55', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep055.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep055_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 56, 'Episode 56', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep056.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep056_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 57, 'Episode 57', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep057.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep057_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 58, 'Episode 58', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep058.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep058_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 59, 'Episode 59', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep059.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep059_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 60, 'Episode 60', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep060.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep060_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 61, 'Episode 61', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep061.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep061_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 62, 'Episode 62', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep062.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep062_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 63, 'Episode 63', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep063.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep063_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 64, 'Episode 64', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep064.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep064_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 65, 'Episode 65', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep065.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep065_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 66, 'Episode 66', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep066.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep066_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 67, 'Episode 67', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep067.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep067_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 68, 'Episode 68', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep068.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep068_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 69, 'Episode 69', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep069.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep069_540p.mp4', 0, false, 0, 0, true, NOW(), NOW()),
(gen_random_uuid(), 'ugg83k4tufn3vmqjtydijhy1', 70, 'Episode 70', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep070.mp4', 'https://stream.shortlovers.id/netshortv2/manisnya-cinta-tak-sehangat-uang/ep070_540p.mp4', 0, false, 0, 0, true, NOW(), NOW());

-- Update totalEpisodes count
UPDATE dramas SET "totalEpisodes" = 70 WHERE id = 'ugg83k4tufn3vmqjtydijhy1';
