#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Netshort V2 Scraper - KingShort Pipeline
=========================================
Downloads 4 target dramas from Vidrama/NetshortV2 provider,
re-encodes to MP4 + 540p, uploads to Cloudflare R2,
then registers to KingShort Postgres DB directly via psycopg2.

API Endpoints (discovered via browser interception):
  Detail:  GET https://vidrama.asia/api/netshortv2/detail/{drama_id}?lang=id_ID
  Episode: GET https://vidrama.asia/api/netshortv2/episode/{drama_id}/{ep_no}?lang=id_ID

Video URLs are signed MP4s from awscdn.netshort.com (~1 hour TTL).
Must be downloaded immediately after fetching.
"""
import sys
import requests
import boto3
import subprocess
import time
import json
import tempfile
import psycopg2
import psycopg2.extras
from pathlib import Path
from botocore.config import Config
from datetime import datetime

# ── Config ───────────────────────────────────────────────────────────────────
DB_URL      = 'postgresql://supabase_admin:GoZViiH1AXLl73BqLdKDtpeGgwUzfW64@141.11.160.187:5432/postgres'

API_BASE    = 'https://api.shortlovers.id'
ADMIN_KEY   = '00ca04e3e2702be565d7bf44e783255247708289bce9b2fb6187a2e117f87fd14'
ADMIN_HDR   = {'x-admin-key': ADMIN_KEY, 'Content-Type': 'application/json'}

R2_ENDPOINT = 'https://a142d3b29a5d64943cb251157e25eaf3.r2.cloudflarestorage.com'
R2_KEY_ID   = '07c99c897986ea52703c1285308d5e2c'
R2_SECRET   = '44788d376ffb216e1e73784b6fe1ff1423607928898a87c50819b52cdfc12e44'
R2_BUCKET   = 'shortlovers'
R2_PUBLIC   = 'https://stream.shortlovers.id'

VIDRAMA_API = 'https://vidrama.asia/api/netshortv2'
WEB_HDRS    = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Referer': 'https://vidrama.asia/',
}

TEMP_DIR = Path(tempfile.gettempdir()) / 'ns2_scraper'
TEMP_DIR.mkdir(exist_ok=True)

# ── Target Dramas (priority ordered) ──────────────────────────────────────────
TARGET_DRAMAS = [
    {
        'slug': 'pemilik-kitab-pedang',
        'drama_id': '2036690458087784450',
        'r2_prefix': 'netshortv2/pemilik-kitab-pedang',
    },
    {
        'slug': 'jenderal-masakanku-siap',
        'drama_id': '2045396177699995650',
        'r2_prefix': 'netshortv2/jenderal-masakanku-siap',
    },
    {
        'slug': 'kode-cinta-robot',
        'drama_id': '2044326309693227010',
        'r2_prefix': 'netshortv2/kode-cinta-robot',
    },
    {
        'slug': 'dia-kembali-dari-balik-legenda',
        'drama_id': '2011980833696841730',
        'r2_prefix': 'netshortv2/dia-kembali-dari-balik-legenda',
    },
]

# ── DB Helpers ────────────────────────────────────────────────────────────────
def get_db():
    return psycopg2.connect(DB_URL)

def generate_cuid():
    """Simple CUID-like ID for Postgres (fallback, actual CUID generated by Postgres trigger)."""
    import random, string
    return 'c' + ''.join(random.choices(string.ascii_lowercase + string.digits, k=24))

def db_get_or_create_drama(conn, detail, slug, cover_r2_url):
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    
    # Check if exists by title
    cur.execute("SELECT id FROM dramas WHERE title = %s LIMIT 1", (detail['title'],))
    row = cur.fetchone()
    if row:
        print(f"  Drama already in DB. ID: {row['id']}")
        return row['id']
    
    genres = detail.get('labels', [])
    if not genres:
        genres = ['Drama']
    
    drama_id = generate_cuid()
    now = datetime.utcnow()
    
    cur.execute("""
        INSERT INTO dramas (id, title, description, cover, genres, tag_list, total_episodes,
            rating, views, likes, review_count, average_rating, status, is_vip, is_featured,
            is_active, age_rating, cast, country, language, created_at, updated_at)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        RETURNING id
    """, (
        drama_id,
        detail['title'],
        detail.get('description', detail['title']),
        cover_r2_url,
        json.dumps(genres),
        json.dumps([]),
        detail.get('totalEpisodes', 0),
        0.0, 0, 0, 0, 0.0,
        'completed' if detail.get('isFinished') else 'ongoing',
        False, False, True, 'all',
        json.dumps([]),
        'China', 'Indonesia',
        now, now
    ))
    result = cur.fetchone()
    conn.commit()
    new_id = result['id']
    print(f"  Drama created in DB. ID: {new_id}")
    return new_id

def db_upsert_episode(conn, drama_db_id, ep_no, url_720, url_540=None):
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    now = datetime.utcnow()
    
    # Check if exists
    cur.execute("SELECT id FROM episodes WHERE drama_id = %s AND episode_number = %s", (drama_db_id, ep_no))
    row = cur.fetchone()
    
    if row:
        # Update
        cur.execute("""
            UPDATE episodes SET video_url = %s, video_url_540p = %s, updated_at = %s
            WHERE id = %s
        """, (url_720, url_540, now, row['id']))
    else:
        # Insert
        ep_id = generate_cuid()
        cur.execute("""
            INSERT INTO episodes (id, drama_id, episode_number, title, video_url, video_url_540p,
                duration, is_vip, coin_price, views, is_active, release_date, created_at, updated_at)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, (
            ep_id, drama_db_id, ep_no, f'Episode {ep_no}',
            url_720, url_540,
            0, False, 0, 0, True,
            now, now, now
        ))
    conn.commit()

def db_update_total_episodes(conn, drama_db_id, total):
    cur = conn.cursor()
    cur.execute("UPDATE dramas SET total_episodes = %s WHERE id = %s", (total, drama_db_id))
    conn.commit()

# ── R2 Helpers ─────────────────────────────────────────────────────────────────
def get_r2():
    return boto3.client(
        's3',
        endpoint_url=R2_ENDPOINT,
        aws_access_key_id=R2_KEY_ID,
        aws_secret_access_key=R2_SECRET,
        config=Config(signature_version='s3v4'),
        region_name='auto',
    )

def r2_exists(r2, key):
    try:
        r2.head_object(Bucket=R2_BUCKET, Key=key)
        return True
    except:
        return False

def r2_upload(r2, local_path, key, content_type='video/mp4'):
    r2.upload_file(
        str(local_path), R2_BUCKET, key,
        ExtraArgs={'ContentType': content_type},
        Config=boto3.s3.transfer.TransferConfig(
            multipart_threshold=30 * 1024 * 1024,
            multipart_chunksize=10 * 1024 * 1024,
        )
    )
    return f"{R2_PUBLIC}/{key}"

# ── Vidrama API Helpers ────────────────────────────────────────────────────────
def get_drama_detail(drama_id):
    url = f"{VIDRAMA_API}/detail/{drama_id}?lang=id_ID"
    r = requests.get(url, headers=WEB_HDRS, timeout=15)
    data = r.json()
    if data.get('code') != 200:
        raise Exception(f"Failed to get detail: {data}")
    return data['data']

def get_episode_url(drama_id, ep_no, retries=3):
    """Returns (mp4_url_720p, episode_id) or (None, None)."""
    url = f"{VIDRAMA_API}/episode/{drama_id}/{ep_no}?lang=id_ID"
    for attempt in range(retries):
        try:
            r = requests.get(url, headers=WEB_HDRS, timeout=15)
            data = r.json()
            if data.get('code') == 200:
                ep_data = data['data']
                videos  = ep_data.get('videos', [])
                ep_id   = ep_data.get('episodeId', '')
                # Prefer 720p for encode input
                for q in ['720p', '1080p', '540p', '480p', '360p']:
                    for v in videos:
                        if v.get('quality') == q:
                            return v['url'], ep_id
                if videos:
                    return videos[0]['url'], ep_id
        except Exception as e:
            print(f"    get_url attempt {attempt+1}: {e}")
            time.sleep(2)
    return None, None

# ── Download & Encode ───────────────────────────────────────────────────────────
def download_mp4(url, out_path, label=''):
    print(f"    Downloading {label}...", end='', flush=True)
    with requests.get(url, stream=True, timeout=180, headers=WEB_HDRS, verify=False) as resp:
        resp.raise_for_status()
        done = 0
        with open(out_path, 'wb') as f:
            for chunk in resp.iter_content(chunk_size=2 * 1024 * 1024):
                f.write(chunk)
                done += len(chunk)
    mb = done / (1024 * 1024)
    print(f" {mb:.1f}MB OK")

def encode_720_and_540(inp, out_720, out_540):
    """Returns True if 540p also succeeded."""
    # 720p faststart re-encode
    cmd = [
        'ffmpeg', '-y', '-i', str(inp),
        '-c:v', 'libx264', '-crf', '26',
        '-maxrate', '1500k', '-bufsize', '3000k',
        '-c:a', 'aac', '-b:a', '128k',
        '-movflags', '+faststart',
        '-loglevel', 'error', str(out_720)
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if res.returncode != 0:
        # Fallback stream copy
        cmd2 = ['ffmpeg', '-y', '-i', str(inp), '-c', 'copy',
                 '-movflags', '+faststart', '-loglevel', 'error', str(out_720)]
        res2 = subprocess.run(cmd2, capture_output=True, text=True, timeout=300)
        if res2.returncode != 0:
            raise Exception(f"ffmpeg 720p failed: {res2.stderr[-200:]}")
    
    # 540p
    cmd3 = [
        'ffmpeg', '-y', '-i', str(out_720),
        '-vf', 'scale=-2:540',
        '-c:v', 'libx264', '-crf', '28', '-preset', 'fast',
        '-c:a', 'aac', '-b:a', '96k',
        '-movflags', '+faststart',
        '-loglevel', 'error', str(out_540)
    ]
    res3 = subprocess.run(cmd3, capture_output=True, text=True, timeout=600)
    return res3.returncode == 0

# ── Process one drama ──────────────────────────────────────────────────────────
def process_drama(cfg, r2, conn):
    slug     = cfg['slug']
    drama_id = cfg['drama_id']
    prefix   = cfg['r2_prefix']
    
    print(f"\n{'='*65}")
    print(f"[DRAMA] {slug}")
    print(f"[ID]    {drama_id}")
    
    # 1. Detail
    print("[1/4] Fetching detail...")
    try:
        detail = get_drama_detail(drama_id)
    except Exception as e:
        print(f"  FAILED: {e}")
        return
    
    title     = detail['title']
    total_eps = detail['totalEpisodes']
    episodes  = detail.get('episodes', [])
    print(f"  Title: {title} | {total_eps} eps | finished={detail.get('isFinished', False)}")
    
    # 2. Cover
    print("[2/4] Cover...")
    cover_key = f"{prefix}/cover.webp"
    cover_url_r2 = f"{R2_PUBLIC}/{cover_key}"
    
    if not r2_exists(r2, cover_key):
        try:
            cov_r = requests.get(detail['cover'], headers=WEB_HDRS, timeout=30, verify=False)
            cov_path = TEMP_DIR / f"{slug}_cover"
            cov_path.write_bytes(cov_r.content)
            r2_upload(r2, cov_path, cover_key, 'image/webp')
            cov_path.unlink()
            print(f"  Uploaded: {cover_url_r2}")
        except Exception as e:
            print(f"  Cover failed (non-fatal): {e}")
            cover_url_r2 = detail['cover']  # fallback to original URL
    else:
        print("  Already in R2")
    
    # 3. Register drama
    print("[3/4] Registering in DB...")
    try:
        drama_db_id = db_get_or_create_drama(conn, detail, slug, cover_url_r2)
    except Exception as e:
        print(f"  DB error: {e}")
        drama_db_id = None
    
    # 4. Episodes
    print(f"[4/4] Processing {len(episodes)} episodes...")
    success, skipped, failed = 0, 0, []
    
    for ep_data in episodes:
        ep_no  = ep_data['episodeNo']
        locked = ep_data.get('isLocked', False)
        
        key_720 = f"{prefix}/ep{ep_no:03d}.mp4"
        key_540 = f"{prefix}/ep{ep_no:03d}_540p.mp4"
        
        # Already in R2
        if r2_exists(r2, key_720):
            print(f"  ep{ep_no:03d}: SKIP (in R2)")
            skipped += 1
            if drama_db_id:
                url_540 = f"{R2_PUBLIC}/{key_540}" if r2_exists(r2, key_540) else None
                db_upsert_episode(conn, drama_db_id, ep_no, f"{R2_PUBLIC}/{key_720}", url_540)
            continue
        
        if locked:
            print(f"  ep{ep_no:03d}: SKIP (VIP locked)")
            skipped += 1
            continue
        
        print(f"  ep{ep_no:03d}: processing...")
        
        # Get signed video URL right before download
        video_url, ep_id = get_episode_url(drama_id, ep_no)
        if not video_url:
            print(f"  ep{ep_no:03d}: FAILED (no URL)")
            failed.append(ep_no)
            continue
        
        raw  = TEMP_DIR / f"{slug}_ep{ep_no:03d}_raw.mp4"
        o720 = TEMP_DIR / f"{slug}_ep{ep_no:03d}_720p.mp4"
        o540 = TEMP_DIR / f"{slug}_ep{ep_no:03d}_540p.mp4"
        
        try:
            download_mp4(video_url, raw, f"ep{ep_no:03d}")
            
            print(f"    Encoding...", end='', flush=True)
            has_540 = encode_720_and_540(raw, o720, o540)
            print(" OK")
            raw.unlink(missing_ok=True)
            
            print(f"    Uploading 720p...", end='', flush=True)
            url_720 = r2_upload(r2, o720, key_720)
            print(f" OK")
            
            url_540_r2 = None
            if has_540 and o540.exists():
                print(f"    Uploading 540p...", end='', flush=True)
                url_540_r2 = r2_upload(r2, o540, key_540)
                print(f" OK")
            
            if drama_db_id:
                db_upsert_episode(conn, drama_db_id, ep_no, url_720, url_540_r2)
                print(f"    DB: OK")
            
            success += 1
            
        except Exception as e:
            print(f"\n  ep{ep_no:03d}: ERROR: {e}")
            failed.append(ep_no)
        finally:
            for p in [raw, o720, o540]:
                try:
                    if p.exists(): p.unlink()
                except:
                    pass
    
    # Update total_episodes count
    if drama_db_id and success > 0:
        free_count = sum(1 for e in episodes if not e.get('isLocked'))
        db_update_total_episodes(conn, drama_db_id, free_count + skipped)
    
    print(f"\n  --- {slug} done ---")
    print(f"  OK: {success} | Skip: {skipped} | Fail: {len(failed)} {failed if failed else ''}")


# ── Main ────────────────────────────────────────────────────────────────────────
def main():
    print("[START] NetshortV2 Scraper - KingShort Pipeline")
    print(f"[INFO] {len(TARGET_DRAMAS)} dramas queued")
    print()
    
    r2 = get_r2()
    conn = get_db()
    print("[DB] Connected to Postgres")
    
    for cfg in TARGET_DRAMAS:
        process_drama(cfg, r2, conn)
    
    conn.close()
    print(f"\n{'='*65}")
    print("[DONE] ALL DRAMAS PROCESSED!")

if __name__ == "__main__":
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    main()
